### PR TITLE
fix issue #3 : Create StreamDescriptionOverlay component

### LINKED ISSUE #3: Create StreamDescriptionOverlay component
Create a component for the stream description overlay that is to be shown when the user taps on a stream on the Explore streams screen. As props, take:
- A boolean `open`, that decides if the overlay is open or not.
- A `stream` object of type `IStream`.
- A boolean that specifies if the stream is followed by the user or not.
- An `onButtonPress` function of type `() => void`: call this function when the user taps on the Subscribe (or Unsubscribe) button.

[`Overlay`](https://react-native-elements.github.io/react-native-elements/docs/overlay.html) from React Native Elements seems good for making this.

### PR DESCRIPTION
**Pull request by BipplavTiwari**
Created StreamDescriptionOverlay component.
Resolves #3

### CODE REVIEW

File: ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+    return (
+    <View style={Overlaystyles.component}>
+      <Text style={{color: "grey"}}><Text style={Overlaystyles.followers}>{props.stream.followed_by}</Text> Subscribers</Text>
+    </View>
+    );
+  };
+  const MyButton=(props : Props)=>{
+    const [following,changefollowing]=useState(props.isFollowed);
+    const [myIcon, setmyIcon] = following? useState("bell-slash") : useState("bell");
+    const [buttonColor, setbuttonColor] = following? useState("#1762e3") : useState("#ff0000");
```
Comment (mridul911) [inline ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx]: Instead of defining these states directly use this condition inside Icon.Button like this.
name={following ? "bell-slash" : "bell"}

File: ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+    function changeit(){
```
Comment (mridul911) [inline ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx]: use arrow functions instead of normal one.

**Review by mridul911 — APPROVED** [review]

File: ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+            </Icon.Button>                    
+        }
+      </View>
+    );
+  };
+    const StreamDescriptionOverlay = (props : Props) => {
+    const [visible, setVisible] = useState(props.open);
+    const toggleOverlay = () => {
+      setVisible(!visible);
+    };
```
Comment (mridul911) [inline ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx]: don't write separate function for this directly use this like onBackDropPress{()=>setVisible(false)}

**Review by mridul911 — APPROVED** [review]

File: ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx (hunk 1 above)
Comment (BipplavTiwari) [reply ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx]: Made suggested changes.

File: ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx (hunk 2 above)
Comment (BipplavTiwari) [reply ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx]: Made suggested changes.

File: ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx (hunk 3 above)
Comment (BipplavTiwari) [reply ui/StreamDescriptionOverlayComponent/StreamDescriptionOverlay-Component.tsx]: Made suggested changes.
