### PR TITLE
Fix issue #8: Create Login Screen

### LINKED ISSUE #8: Create login screen
Create the login screen. UI design is up to you!

### PR DESCRIPTION
**Pull request by kartikcode**
Fixes #8 .

### CODE REVIEW

**Comment by kartikcode** [comment]
Snaps
Screenshot_20200724-181755_Video Player
Screenshot_20200724-181800_Video Player
Screenshot_20200724-181815_Video Player (1)
Screenshot_20200724-181821_Video Player

**Comment by kartikcode** [comment]
The main login screen has a responsive layout and hides the image when keyboard pops out.
UPD: Working preview can be found [here](https://drive.google.com/file/d/1mgOH4r5cFxlVzYawh6WMm18nyCRNQjRE/view?usp=sharing).

File: ui/screens/login/LoginComponent.tsx [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+        }
+    }, [])
+
+    const _keyboardDidShow = () => {
+        setKeyboardVisibility(true);
+    };
+
+    const _keyboardDidHide = () => {
+        setKeyboardVisibility(false);
+    };
```
Comment (nilaymaj) [inline ui/screens/login/LoginComponent.tsx]: `_keyboardDidShow` and `_keyboardDidHide` seem to be used only in the effect above - in that case, instead of having separate functions, just directly use `setKeyboardVisibility` inside the effect.

File: ui/screens/login/LoginComponent.tsx [hunk 2]
```diff
@@ -0,0 +1,174 @@
...
+                    <View style={styles.section}>
+                        <MaterialIcons name="lock-outline" size={20} />
+                        <TextInput
+                            placeholder="Password"
+                            style={styles.inpText}
+                            secureTextEntry={secureState}
+                            onChange={handlePassword}
+                        />
+                        {password !== "" ?
+                            <MaterialIcons name="remove-red-eye" size={20} onPress={() => handleSecureText()} /> : null}
```
Comment (nilaymaj) [inline ui/screens/login/LoginComponent.tsx]: Just a little change: `() => handleSecureText()` can probably directly be written as `handleSecureText`.

File: ui/screens/login/LoginComponent.tsx [hunk 3]
```diff
@@ -0,0 +1,174 @@
...
+            </View>
+        );
+}
+    
+export default LoginComponent;
+
+const { width, height } = Dimensions.get("screen");
+const inp_width = width * 0.7;
+const height_img = height * 0.5 * 0.6;
+const width_img = height_img * 1.1;
```
Comment (nilaymaj) [inline ui/screens/login/LoginComponent.tsx:116]: camelCase please :sweat_smile:

File: App.tsx [hunk 4]
```diff
@@ -1,13 +1,11 @@
...
 import { StyleSheet, Text, View } from "react-native";
+import StackNavigator from "./ui/screens/login/RootStack";
 
 export default function App() {
   return (
-    <View style={styles.container}>
-      <Text>Open up App.tsx to start working on your app!</Text>
-      <StatusBar style="auto" />
-    </View>
+    <StackNavigator/>
```
Comment (nilaymaj) [inline App.tsx]: This is great for testing, but now that the work is done you can change it back to the default.

File: package.json [hunk 5]
```diff
@@ -8,13 +8,26 @@
...
     "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
+    "react-native-animatable": "^1.3.3",
     "react-native-elements": "^2.0.4",
-    "react-native-web": "~0.11.7"
+    "react-native-gesture-handler": "^1.7.0",
+    "react-native-keyboard": "^2.0.1",
+    "react-native-keyboard-aware-scroll-view": "^0.9.1",
+    "react-native-reanimated": "^1.10.1",
+    "react-native-safe-area-context": "^3.1.1",
+    "react-native-screens": "^2.9.0",
```
Comment (nilaymaj) [inline package.json:25]: Are you still using `react-native-screens` and `react-native-animated` in your code? If not, remove these packages with npm or yarn.

**Review by nilaymaj — COMMENTED** [review]
The UI rocks :heart:. Just a few changes required before merging.
Also, I've pushed a commit that adds a Prettier configuration to the project. Pull it and run Prettier on your changes please.

File: package.json (hunk 5 above)
Comment (kartikcode) [reply package.json:25]: Both the packages are actually dependencies for `react-navigation-stack`.

**Comment by kartikcode** [comment]
All the mentioned changes have been done. Also, I didn't have Prettier extension installed on VSC originally, which was the cause for irregular formatting. The same has been updated too!!
